### PR TITLE
Add lastPoint and Padding

### PR DESCRIPTION
**Pull request by Findus23**
Two more features that I need.
- a last point to quickly see the last 
- add suport for padding that will be colored in the background color and is added to the total size (do you think it would be better if the size stayed the defined width and height and the content gets smaller)
- I noticed that the dotRadius was used as the diameter and fixed it

Example (with exaggerated colors)
sparkline

### CODE REVIEW

**Comment by davaxi** [comment]
Hi,

I check this Pull Request this week. Thank for your collaboration.

**Comment by Findus23** [comment]
I won't have time in the next weeks to refactor the code.
If you want to you can ignore my pull request and apply the changes to your refactored version.

**Comment by davaxi** [comment]
I work this week to integrate your PR on next release. 

For the last point, i think to create generique method for add point to specific index of data. 

Why you multiply by 2 dots ?

**Comment by Findus23** [comment]
I forgot to answer, but I multiplied by two as the function sets the radius but we are using width and height (so the diameter)
It doesn't really matter but it should be documented if one should set the diameter or radius.

**Comment by davaxi** [comment]
I publish in release 1.1.0 method to addPoint to minimum / maximum / first / last / (or by index). You can use created method with index 'last' to add point to last index.

For padding, i work to publish new release before end of this week.

**Comment by davaxi** [comment]
Release 1.1.1 with setPadding method published :)

**Comment by Findus23** [comment]
Wow, you're fast.

If I find time I'll test if it works the way I need it this weekend.

**Comment by Findus23** [comment]
Hi, 
It's looking good, but I still disagree with the following:
https://github.com/davaxi/Sparkline/blob/f88e58749fef47cc5b71095c033b3d214fcdf56c/src/Sparkline/Picture.php#L135-L142
According to [the PHP doc](https://secure.php.net/manual/en/function.imagefilledellipse.php), the parameters are width and height, but you are passing the radius, which is is only the half width and height.

**Comment by Findus23** [comment]
Another thing:
If all points have the same value, I'd expect no minimum/maximum dot instead of an exception.

https://github.com/davaxi/Sparkline/blob/f88e58749fef47cc5b71095c033b3d214fcdf56c/src/Sparkline/PointTrait.php#L47-L50
```
[Fri Dec  8 22:16:55 2017] PHP Fatal error:  Uncaught InvalidArgumentException: Invalid index : minimum in /home/lukas/git/Sparkline/src/Sparkline/PointTrait.php:62
Stack trace:
#0 /home/lukas/git/Sparkline/src/Sparkline/PointTrait.php(26): Davaxi\Sparkline->checkPointIndex('minimum')
#1 /home/lukas/git/Sparkline/test.php(31): Davaxi\Sparkline->addPoint('minimum', 10, '#ff7f7f')
#2 {main}
  thrown in /home/lukas/git/Sparkline/src/Sparkline/PointTrait.php on line 62
```

**Comment by davaxi** [comment]
For first comment, your are right. I update with radius * 2.

For mapping / min - max... i don't now realy good workflow... if not existing min/max value what i do ? I can create method to check if existing distinct values, and user check before using min/max index.  What do you think ?

**Comment by Findus23** [comment]
Honestly I am not sure what the intended behavior should be. Maybe the best would be simply not painting the dot if there is no minimum/maximum

**Comment by davaxi** [comment]
Fixed in 1.1.2

**Comment by Findus23** [comment]
Hi,

It took me a long time to notice that the `$sparkline->addPoint` needs to be run after adding the data as otherwise no or wrong dots appear.

Maybe make the warning in the README more clear or even throw a warning when there is no data while running `addPoint`.

**Pull request closed without merging**
